### ISSUE TITLE
grammarExpression (SELECT IN) is not supported for MySQLDialect

### ISSUE THREAD

**Issue by ichan0220** [xinix-technology/norm#70]
Hello, 

I have problem with grammarExpression with operator "IN", is should be "SELECT * FROM WHERE 'field' IN ('1','2','3').
but I got error " is Not Supported ".

please your update for MySql Dialect

Thank You

**Comment by krisanalfa** [comment]
I hope you guys can wait until this noon, because the documentation is being completed now. Thanks for your kindness and sorry for inconvenience.

**Comment by krisanalfa** [comment]
Hi, @ichan0220, could you reproduce this issue? Mine is not problem.

**Comment by januarsiregar** [comment]
Problem is solve, solving on sqldialet for grammar expression , not on mysql dialect. Because the expression is for all sql langueate not only for mysql dialect. please use version 1.0.0

**Comment by krisanalfa** [comment]
@januarsiregar +1
